### ISSUE TITLE
Causemos rather than CauseMos

### ISSUE THREAD

**Issue by kwalcock** [WorldModelers/WorldModelers#38]
@bgyori, in trying to write Causemos consistently myself, I noticed that the workflow graphics (both the 5 and 3 workflow versions) have it written CauseMos.  The documentation from Uncharted Software has Causemos everywhere.  If the graphic isn't too difficult to change, it should probably be made to match.

**Comment by kwalcock** [comment]
@bgyori, did you notice this?

**Comment by bgyori** [comment]
Thanks, I will fix this.

**Comment by kwalcock** [comment]
Thank you!
