### ISSUE TITLE
Organizing the README around workflows

### ISSUE THREAD

**Issue by bgyori** [WorldModelers/WorldModelers#5]
I am wondering what the best way is to organize the README to help users quickly get started with our systems. I think we might be able to think about various levels of integration resulting in increasingly sophisticated workflows. Here are some workflows that I think would be practically relevant:
1. User compiles document corpus manually and processes it with a single reading system, then uses the given reader's outputs directly for analysis.
2. User compiles document corpus manually and processes it with one or more reading systems, then uses INDRA to perform assembly and uses INDRA's output for analysis.
3. The document corpus is managed using DART, documents are then processed with one or more reading systems and the result are assembled with INDRA, then the user uses INDRA's output for analysis.
4. The user starts with (2) or (3) to obtain INDRA outputs and then loads these into CauseMos for interactive exploration and analysis.
5. The user starts with (4) and also wants to be able to add their own documents during runtime requiring DART, readers, and INDRA to be running as services.

Orthogonal to all of these is ontology augmentation: this could be relevant for any of the workflows 1-5 and comes with its own set of tools. Perhaps describing the specific systems in the context of these workflows would be better than having a more or less flat list as in the initial README currently.

**Comment by kwalcock** [comment]
Setting up Eidos to run stand-alone vs. with DART to read a large corpus vs. with DART for regrounding are all different.  We can work with or without docker, with or without sbt, with or without grounding, on plain text or on CDRs, etc.  It seems like it would be helpful to limit the possibilities to a small set as suggested if only to limit the documentation effort, both effort to write it and to understand it.

**Comment by kwalcock** [comment]
We're working on it...
